### ISSUE TITLE
Вопрос 1. Прокомментировать код

### ISSUE THREAD

**Issue by nzhukov** [python-advance/sem6-lr4-Kseniaveh#1]
https://github.com/python-advance/sem6-lr4-Kseniaveh/blob/8016fdc5760e2312a0e5a18845fd461c7dd8e984/task.py#L134

В особенности, что такое ```left```, ```right```, ```result``` и для чего они требуются?

**Comment by Kseniaveh** [comment]
Объяснение на примере xor. Чтобы получить xor, нам нужна формула (~x & y) | (x & ~y)
xor  = (~x & y) | (x & ~y) 
1) left - отвечает за левую часть формулы, то есть (~x & y)  
left = PerAnd.func2(not_x, y)
2) right - отвечает за правую часть формулы (x & ~y)
right = PerAnd.func2(x, not_y)
3) Объединяем это все  (~x & y) | (x & ~y) 
result = PerOr.func2(left, right)
Это было использовано с целью, чтобы не тянуть огромную формулу, а разбить ее на кусочки, как последовательные шаги

**Comment by nzhukov** [comment]
👍
